### ISSUE TITLE
Impossible to check instance health while Craft is offline

### ISSUE THREAD

**Issue by josephkerkhof** [jasonmccallister/craft-healthz#3]
Craft returns a 503 error while performing a health check on this URL, which marks the instance (or pod) unhealthy and scheduled for replacement. There may be valid reasons why the site is offline (temporary or otherwise) so this feels like a bug.

**Comment by cdenneen** [comment]
@jasonmccallister will this be added?

**Comment by jasonmccallister** [comment]
Late to reply here, but I'm not really maintaining this plugin going forward. Craft 3.5.6 [added a native health check endpoint](https://craftcms.com/knowledge-base/configuring-load-balanced-environments#health-check-endpoint) that should be used instead. This endpoint will return true even if updates are pending, something this plugin can't really offer. See the [changelog notes here](https://github.com/craftcms/cms/blob/3.8/CHANGELOG.md#356---2020-08-25).

**Comment by jasonmccallister** [comment]
I stand completely corrected because of this: https://github.com/jasonmccallister/craft-healthz/pull/4/files

I'm willing to merge and cut a release if the changes in 3.5.6 don't meet your needs.
